import Icon from "@/components/ui/Icon";

export default function ReportSummary({ reportType }: { reportType: string }) {
  return (
    <div className="space-y-8 bg-[#171f33] border border-[#464554]/10 rounded-3xl p-6 md:p-10 shadow-sm print:border-none print:shadow-none print:p-0 print:bg-transparent vibrant-shadow">
      <div className="flex justify-between items-center pb-6 border-b border-[#464554]/20">
        <div>
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 vibrant-gradient rounded-lg flex items-center justify-center text-white">
              <Icon name="architecture" className="text-lg" />
            </div>
            <h2 className="font-display text-xl font-extrabold text-[#dae2fd]">JMMS Summary</h2>
          </div>
          <p className="text-[10px] text-[#908fa0] mt-1 font-mono uppercase tracking-widest">{reportType} (July 2026)</p>
        </div>
        <div className="text-right text-[10px] font-mono uppercase text-[#908fa0]">
          <div>Export Date: {new Date().toISOString().split("T")[0]}</div>
          <div className="mt-0.5">Generated by: Admin User</div>
        </div>
      </div>

      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        {[
          { label: "Complaints Logged", val: "1,248 Tickets", color: "text-[#c0c1ff]" },
          { label: "Resolution Rate", val: "94.2%", color: "text-[#4edea3]" },
          { label: "Pending Backlogs", val: "42 Tickets", color: "text-[#ffb2b7]" },
          { label: "Avg Resolution Time", val: "3.2 Hours", color: "text-[#dae2fd]" },
        ].map((metric, idx) => (
          <div key={idx} className="p-5 bg-[#131b2e] border border-[#464554]/20 rounded-2xl">
            <span className="text-[10px] font-mono uppercase tracking-wider text-[#908fa0] block">{metric.label}</span>
            <span className={`text-2xl font-black mt-2 block ${metric.color}`}>{metric.val}</span>
          </div>
        ))}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 pt-2 text-xs">
        <div className="space-y-3">
          <h4 className="font-bold text-[#dae2fd] text-xs uppercase tracking-wider border-b border-[#464554]/20 pb-2">Department Output</h4>
          <div className="space-y-2 text-[#c7c4d7]">
            <div className="flex justify-between py-1 border-b border-[#464554]/10">
              <span className="font-bold text-[#dae2fd]">Electrical Division</span>
              <span>42% (88% resolved)</span>
            </div>
            <div className="flex justify-between py-1 border-b border-[#464554]/10">
              <span className="font-bold text-[#dae2fd]">Plumbing Division</span>
              <span>28% (94% resolved)</span>
            </div>
            <div className="flex justify-between py-1 border-b border-[#464554]/10">
              <span className="font-bold text-[#dae2fd]">HVAC Division</span>
              <span>15% (90% resolved)</span>
            </div>
          </div>
        </div>

        <div className="space-y-3">
          <h4 className="font-bold text-[#dae2fd] text-xs uppercase tracking-wider border-b border-[#464554]/20 pb-2">Technician Compliance</h4>
          <div className="space-y-2 text-[#c7c4d7]">
            <div className="flex justify-between py-1 border-b border-[#464554]/10">
              <span className="font-bold text-[#dae2fd]">Rajesh Sharma (Plumber)</span>
              <span className="text-[#4edea3]">98% SLA score</span>
            </div>
            <div className="flex justify-between py-1 border-b border-[#464554]/10">
              <span className="font-bold text-[#dae2fd]">Mohit Kumar (Electrician)</span>
              <span className="text-[#4edea3]">94% SLA score</span>
            </div>
          </div>
        </div>
      </div>

      <div className="pt-6 border-t border-[#464554]/20 text-center text-[10px] text-[#908fa0] font-mono uppercase tracking-wider">
        *** Lumina Prism Engine — Jain International Residential School ***
      </div>
    </div>
  );
}
