import Icon from "@/components/ui/Icon";

export type ComplaintRow = {
  ticketId: string;
  category: string;
  priority: string;
  description: string;
  postedBy: string;
  technicianName: string;
  status: string;
};

export type TechnicianRow = {
  technicianName: string;
  totalTickets: number;
  currentStatus: string;
};

export type ReportData = {
  totalComplaints: number;
  resolutionRate: number;
  pendingBacklog: number;
  inProgress: number;
  departmentOutput: { category: string; sharePercent: number; resolvedPercent: number }[];
  technicianCompliance: { name: string; ticketCount: number; slaScore: number }[];
  complaintRows: ComplaintRow[];
  technicianRows: TechnicianRow[];
  generatedAt: string;
  generatedBy: string;
};

export default function ReportSummary({ reportType, data }: Readonly<{ reportType: string; data: ReportData }>) {
  const metrics = [
    { label: "Complaints Logged", val: `${data.totalComplaints.toLocaleString()} Tickets`, color: "text-primary dark:text-[#c0c1ff]" },
    { label: "Resolution Rate", val: `${data.resolutionRate}%`, color: "text-emerald-600 dark:text-[#4edea3]" },
    { label: "Pending Backlogs", val: `${data.pendingBacklog} Tickets`, color: "text-rose-600 dark:text-[#ffb2b7]" },
    { label: "In Progress", val: `${data.inProgress} Tickets`, color: "text-indigo-600 dark:text-[#8083ff]" },
  ];

  return (
    <div className="space-y-8 bg-white dark:bg-[#171f33] border border-slate-200 dark:border-[#464554]/10 rounded-3xl p-6 md:p-10 shadow-sm print:border-none print:shadow-none print:p-0 print:bg-transparent dark:vibrant-shadow">
      <div className="flex justify-between items-center pb-6 border-b border-slate-200 dark:border-[#464554]/20">
        <div>
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 vibrant-gradient rounded-lg flex items-center justify-center text-white">
              <Icon name="architecture" className="text-lg" />
            </div>
            <h2 className="font-display text-xl font-extrabold text-slate-900 dark:text-[#dae2fd]">JMMS Summary</h2>
          </div>
          <p className="text-[10px] text-slate-500 dark:text-[#908fa0] mt-1 font-mono uppercase tracking-widest">{reportType}</p>
        </div>
        <div className="text-right text-[10px] font-mono uppercase text-slate-500 dark:text-[#908fa0]">
          <div>Export Date: {data.generatedAt}</div>
          <div className="mt-0.5">Generated by: {data.generatedBy}</div>
        </div>
      </div>

      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        {metrics.map((metric, idx) => (
          <div key={idx} className="p-5 bg-slate-50 dark:bg-[#131b2e] border border-slate-200 dark:border-[#464554]/20 rounded-2xl">
            <span className="text-[10px] font-mono uppercase tracking-wider text-slate-500 dark:text-[#908fa0] block">{metric.label}</span>
            <span className={`text-2xl font-black mt-2 block ${metric.color}`}>{metric.val}</span>
          </div>
        ))}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 pt-2 text-xs">
        <div className="space-y-3">
          <h4 className="font-bold text-slate-900 dark:text-[#dae2fd] text-xs uppercase tracking-wider border-b border-slate-200 dark:border-[#464554]/20 pb-2">Department Output</h4>
          <div className="space-y-2 text-slate-700 dark:text-[#c7c4d7]">
            {data.departmentOutput.length === 0 ? (
              <p className="text-slate-400 dark:text-[#908fa0] py-2">No complaints in this period.</p>
            ) : (
              data.departmentOutput.map((dept) => (
                <div key={dept.category} className="flex justify-between py-1 border-b border-slate-100 dark:border-[#464554]/10">
                  <span className="font-bold text-slate-900 dark:text-[#dae2fd]">{dept.category}</span>
                  <span>{dept.sharePercent}% ({dept.resolvedPercent}% resolved)</span>
                </div>
              ))
            )}
          </div>
        </div>

        <div className="space-y-3">
          <h4 className="font-bold text-slate-900 dark:text-[#dae2fd] text-xs uppercase tracking-wider border-b border-slate-200 dark:border-[#464554]/20 pb-2">Technician Compliance</h4>
          <div className="space-y-2 text-slate-700 dark:text-[#c7c4d7]">
            {data.technicianCompliance.length === 0 ? (
              <p className="text-slate-400 dark:text-[#908fa0] py-2">No technician accounts found.</p>
            ) : (
              data.technicianCompliance.map((tech) => (
                <div key={tech.name} className="flex justify-between py-1 border-b border-slate-100 dark:border-[#464554]/10">
                  <span className="font-bold text-slate-900 dark:text-[#dae2fd]">{tech.name}</span>
                  {tech.ticketCount > 0 ? (
                    <span className="text-emerald-600 dark:text-[#4edea3]">{tech.slaScore}% SLA score ({tech.ticketCount} tickets)</span>
                  ) : (
                    <span className="text-slate-400 dark:text-[#908fa0] italic">No tickets assigned</span>
                  )}
                </div>
              ))
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
